<?php

/**
 * Implements hook_form_FORM_ID_alter().
 */
function roomify_contact_page_form_contact_site_form_alter(&$form, &$form_state) {
  $unit = rooms_unit_load(1);
  // Set sensible weights on the contact form fields, so that we can add our
  // date fields in the right spot.
  $form['name']['#weight'] = -20;
  $form['mail']['#weight'] = -10;
  $form['subject']['#weight'] = 0;
  $form['message']['#weight'] = 10;
  $form['copy']['#weight'] = 20;
  $form['actions']['#weight'] = 100;

  // Hide the subject field.
  $form['subject']['#access'] = FALSE;

  // Add the Rooms date range fields to the contact form.
  $form['dates'] = rooms_date_range_fields();

  // Make the dates appear above the message.
  $form['dates']['#weight'] = -5;

  // Make the date fields optional.
  $form['dates']['rooms_start_date']['#required'] = FALSE;
  $form['dates']['rooms_end_date']['#required'] = FALSE;

  $form['adults'] = array(
    '#type' => 'select',
    '#title' => t('Adults'),
    '#options' => range(1, $unit->max_sleeps),
  );
  if ($unit->max_children != 0) {
    $form['children'] = array(
      '#type' => 'select',
      '#title' => t('Children'),
      '#options' => range(1, $unit->max_children),
    );
  }
  $form['telephone'] = array(
    '#type' => 'textfield',
    '#title' => t('Telephone'),
    '#weight' => -6,
  );

  $url = explode('/', $_GET['q']);

  if (isset($url[1]) && isset($url[2])) {
    $start = new DateTime($url[1]);
    $end = new DateTime($url[2]);
    $form['dates']['rooms_start_date']['#default_value'] = $start->format('Y-m-d');
    $form['dates']['rooms_end_date']['#default_value'] = $end->format('Y-m-d');
  }
}

/**
 * Implements hook_mail_alter().
 */
function roomify_contact_page_mail_alter(&$message) {
  // Add the Rooms date range fields to the contact page email body, if they
  // were specified.
  if ($message['id'] == 'contact_page_mail') {
    if ($message['params']['rooms_end_date']) {
      array_unshift($message['body'], t('Departure Date') . ': ' . $message['params']['rooms_end_date']);
    }
    if ($message['params']['rooms_start_date']) {
      array_unshift($message['body'], t('Arrival Date') . ': ' . $message['params']['rooms_start_date']);
    }
    if (isset($message['params']['adults'])) {
      array_unshift($message['body'], t('Adults') . ': ' . $message['params']['adults']);
    }
    if (isset($message['params']['children'])) {
      array_unshift($message['body'], t('Children') . ': ' . $message['params']['children']);
    }
    if ($message['params']['rooms_start_date']) {
      array_unshift($message['body'], t('Telephone') . ': ' . $message['params']['telephone']);
    }
  }
}
